name: Build
on:
  push:
    paths:
      - .github/workflows/build.yml
      - VainSabers/**
      - VainSabers.sln
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup dotnet
        uses: actions/setup-dotnet@v5

      - name: Set short git commit SHA
        id: vars
        run: |
          calculatedSha=$(git rev-parse --short ${{ github.sha }})
          echo "COMMIT_SHORT_SHA=$calculatedSha" >> $GITHUB_ENV

      - name: Cache Library
        uses: actions/cache@v5
        with:
          path: VainSabers asset creation/Library
          key: Library-${{ hashFiles('VainSabers asset creation/Assets/**', 'VainSabers asset creation/Packages/**', 'VainSabers asset creation/ProjectSettings/**') }}
          restore-keys: |
            Library-

      - name: Cache Assets
        id: cache-assets
        uses: actions/cache@v5
        with:
          path: |
            VainSabers/VainSabers
            VainSabers/VainSabers.manifest
            VainSabers/vs_assets
            VainSabers/vs_assets.manifest
          key: Assets-${{ hashFiles('VainSabers asset creation/Assets/**', 'VainSabers asset creation/Packages/**', 'VainSabers asset creation/ProjectSettings/**') }}
          restore-keys: |
            Assets-

      - name: Make AssetBundle
        if: ${{ steps.cache-assets.outputs.cache-hit != 'true' }}
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          projectPath: "VainSabers asset creation"
          buildMethod: CreateAssetBundles.BuildAllAssetBundles
          targetPlatform: StandaloneWindows64
          allowDirtyBuild: true

      - name: Initialize Modding Environment
        uses: codeman4033/init-beatsaber@v2
        with:
          version: 1.40.8

      - name: Download dependencies
        run: |
          wget https://beatmods.com/cdn/mod/5b90d82d3a9c095747c0ec8cde199d4c.zip -O SiraUtil-v3.2.1.zip
          wget https://github.com/monkeymanboy/BeatSaberMarkupLanguage/releases/download/v1.12.5/BeatSaberMarkupLanguage-v1.12.5+bs.1.40.0-RELEASE.zip
          unzip SiraUtil-v3.2.1.zip -d Refs
          unzip BeatSaberMarkupLanguage-v1.12.5+bs.1.40.0-RELEASE.zip -d Refs

      - name: Restore dependencies
        run: dotnet restore VainSabers

      - name: Create user file
        run: echo '<?xml version="1.0" encoding="utf-8"?><Project><PropertyGroup><BeatSaberDir>${{github.workspace}}/Refs/</BeatSaberDir></PropertyGroup></Project>' > VainSabers/VainSabers.csproj.user

      - name: Build Release
        id: build-release
        run: dotnet publish VainSabers -r win-x64 -c Release

      - name: Build Debug
        id: build-debug
        run: dotnet publish VainSabers -r win-x64 -c Debug

      - name: Upload Release
        uses: actions/upload-artifact@v7
        with:
          name: VainSabers-${{ env.COMMIT_SHORT_SHA }}-Release.zip
          path: ${{ steps.build-release.outputs.artifactpath }}

      - name: Upload Release
        uses: actions/upload-artifact@v7
        with:
          name: VainSabers-${{ env.COMMIT_SHORT_SHA }}-Debug.zip
          path: ${{ steps.build-debug.outputs.artifactpath }}
      